phone = "+123456789"
mongo_uri = "mongodb://localhost:27017"
device_uuid = None # str(uuid.uuid1())
api_uri = "./api.yaml" # from https://github.com/zhuowei/ClubhouseAPI
max_retries = 5
token_file = None
fresh_interval = 3600
user_limit = 500
first_run = False # not used